### ISSUE TITLE
Using clone(estimator) in cross_val_fit

### ISSUE THREAD

**Issue by BenSeimon** [4Freye/panelsplit#15]
Hey Eric,

Turns out I got a little too excited! I was getting absurd model performance, but it turns out the fix is relatively easy. In fact, I think you realised it, but maybe forgot to implement.

You had an unused import "from sklearn.base import clone". This needs utilising in cross_val_fit, otherwise the estimator object gets updated as you roll through the training data. In other words, when you fit/train on the last set of train_indices, it seems like it's updating all the estimator objects in fitted_estimators. This is what was leading to crazy performance. Just needed the one line fix which I call out below and everything is good as gold. See my comments/edits in CAPSLOCK. Sorry, I was too lazy to create a fork/pull request for this.

def cross_val_fit(self, estimator, X, y, sample_weight=None, n_jobs=1):
        """
        Fit the estimator using cross-validation.

        Parameters:
        - estimator: The machine learning model to be fitted.
        - X: pandas DataFrame. The input features for the estimator.
        - y: pandas Series. The target variable for the estimator.
        - sample_weight: Optional pandas Series or numpy array (default=None). Sample weights for the training data.
        - n_jobs: Optional int (default=1). The number of jobs to run in parallel.

        Returns:
        list of fitted models: List containing fitted models for each split.
        """
        def fit_split(train_indices):
            local_estimator = clone(estimator) #I ADDED THIS LINE HERE
            y_train = y.loc[train_indices].dropna()
            X_train = X.loc[y_train.index]
            if sample_weight is not None:
                sw = sample_weight.loc[y_train.index]
            else:
                sw = None
            return local_estimator.fit(X_train, y_train, sample_weight=sw) #AND UPDATED THIS ONE

        fitted_estimators = Parallel(n_jobs=n_jobs)(
            delayed(fit_split)(train_indices)
            for train_indices, _ in self._split_wrapper(self.split())
        )
        return fitted_estimators

**Comment by 4Freye** [comment]
Thanks for pointing this out. I will update the repo with this! This may help with this issue: https://github.com/4Freye/panelsplit/issues/13

**Comment by 4Freye** [comment]
Just merged it in this [pull request](https://github.com/4Freye/panelsplit/pull/16)

It also fixed the issue i mentioned earlier! Two birds with one stone :)
