### ISSUE TITLE
Allow sliding training window in the future?

### ISSUE THREAD

**Issue by LawrentChen** [4Freye/panelsplit#9]
Awesome job!!

I can't imagine why the scikit-learn official does not have this important function for panel data. You did a great job. It really helps a lot.

However, for now the training set in panelsplit is expanding window only. Will it be possible to allow sliding window in the future?

The idea is like
- [GroupTimeSeriesSplit](https://rasbt.github.io/mlxtend/user_guide/evaluate/GroupTimeSeriesSplit/)  in mlxtend
- [SlidingWindowSplitter](https://www.sktime.net/en/stable/api_reference/auto_generated/sktime.split.SlidingWindowSplitter.html) in sktime

I've found it difficult to be compatible with panel data with these two above, also sktime not straightly compatible with scikit-lean(?)

A lot of thanks again.

**Comment by 4Freye** [comment]
Thanks, I appreciate it! If I understand your requirements correctly, please see the max_train_size argument. That should do the trick!

**Comment by LawrentChen** [comment]
Wow! You've already considered that. It works totally as expected with the `max_train_size` argument. Thank you so much!!

Btw, what's the difference between panelsplit version `cross_val_predict`, `cross_val_fit_predict` and the `cross_val_predict` in scikit-learn.

According to the doc:
panelsplit version `cross_val_predict` "Perform cross-validated predictions using a list of fitted estimators". Does it mean you can assign whatever estimators you want to each test set, as long as they are already fitted?
panelsplit version `cross_val_fit_predict` does not require **fitted** estimators. It will fit the estimators with corresponding training set and then use it to predict the test set in the same split, right?
scikit-learn version `cross_val_predict` says "The data is split according to the cv parameter. Each sample belongs to exactly one test set, and its prediction is computed with an estimator fitted on the corresponding training set." It sounds to me that it does the same thing as the panelsplit version `cross_val_fit_predict`, but not panelsplit version `cross_val_predict`. That is confusing for me due to the function name.

Am I right about this?

**Comment by 4Freye** [comment]
I am closing this issue as it's different than the original question. If you have any more questions please create other issues, thank you!

> panelsplit version cross_val_predict "Perform cross-validated predictions using a list of fitted estimators". Does it mean you can assign whatever estimators you want to each test set, as long as they are already fitted?

Yes! You must provide the same number of estimators as the number of splits, in the form of a list of estimators. This is what is returned when calling cross_val_fit().

> panelsplit version cross_val_fit_predict does not require fitted estimators. It will fit the estimators with corresponding training set and then use it to predict the test set in the same split, right?

Yes!

> scikit-learn version cross_val_predict says "The data is split according to the cv parameter. Each sample belongs to exactly one test set, and its prediction is computed with an estimator fitted on the corresponding training set." It sounds to me that it does the same thing as the panelsplit version cross_val_fit_predict, but not panelsplit version cross_val_predict. That is confusing for me due to the function name.

Yes, I understand the confusion. You are correct that sklearn's cross_val_predict does fit and predict, while PanelSplit's cross_val_predict only predicts. The equivalent of sklearn's cross_val_predict for PanelSplit is cross_val_fit_predict.

I am following the sklearn convention for estimators to have a .fit() argument and a .predict() argument when working in PanelSplit, which is what is intuitive to me.

As a side note, sklearn's cross_val_predict doesn't work with TimeSeriesSplit or PanelSplit, which is what led me to create the functionality for PanelSplit. https://github.com/scikit-learn/scikit-learn/issues/8043

**Comment by LawrentChen** [comment]
Thank you for clarifying my confusion! Sorry for asking irrelevant question following the original issue.

> As a side note, sklearn's cross_val_predict doesn't work with TimeSeriesSplit or PanelSplit, which is what led me to create the functionality for PanelSplit. https://github.com/scikit-learn/scikit-learn/issues/8043

Yes! I also encounter the same issue "ValueError: cross_val_predict only works for partitions". Thank god I found your solution. I still can't understand why the scikit-learn official haven't support this feature. I think your panelsplit should be added to the official some day as such a nice module.
